spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 796214187309-kpall1h7m0hr6elmo492p31kqcgc4mvr.apps.googleusercontent.com
            client-secret: lUUZeTMrePv5rm7AcgKlmAVu
            redirect-uri: http://localhost:8080/auth/login/oauth2/code/google
security:
  jwt:
    key-store: classpath:/keystore/auth_server.keystore
    key-store-password: 123456789
    key-pair-alias: auth_server_keystore
    key-pair-password: 123456789

server:
  servlet:
    context-path: /auth

logging:
  level:
    root: DEBUG
custom:
  cors:
    allowOrigin: http://localhost:8081
    allowMethods: GET, POST, PUT, OPTIONS
    allowHeaders: Content-Type
    allowCredentials: true
    maxAge: 3600