version: "3.6"
services:
  db:
    image: postgres:11.10-alpine
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.type == db

  backend:
    build: ../auth-backend/
    environment:
      SPRING_APPLICATION_NAME: "auth-backend"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/public
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
    depends_on:
      - db
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  auth-db-data:
